In [1]:
import numpy as np

In [7]:
# 0-D tensors / Scalers
a = np.array(4)

In [5]:
a

array(4)

In [9]:
# for check dimension of array
a.ndim

0

In [11]:
# 1-D tensors / Vectors
arr = np.array([1,5,3,6])

In [17]:
print(arr)
arr.ndim

[1 5 3 6]


1

In [19]:
## 2-D tensor / Matrices
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)
mat.ndim

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2